apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helidon-quickstart-mp
  annotations:
    github.com/project-slug: kvfi/helidon-quickstart-mp
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: guests
